# Self-Hosted Github Action Runners on GCP via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml.html
runners:
  - name: gpu-runner
    cloud: aws
    # Cheapest VM on AWS
    instance_type: g4dn.xlarge
    # Ubuntu-20.4, ami image"
    machine_image: ami-06fd8a495a537da8b
    preemptible: false
    workflow: .github/workflows/tests-gpu.yml
    count: 2
    labels:
      - gpu
