# Self-Hosted Github Action Runners on GCP via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml.html
runners:
  - name: gpu-runner
    cloud: aws
    region: eu-west-1
    instance_type: g4dn.xlarge  # Cheapest VM on AWS
    gpu: true
    machine_image: ami-03caf24deed650e2c  # Ubuntu 20.04 in eu-west-1
    preemptible: false
    workflow: .github/workflows/tests-gpu.yml
    count: 1
    labels:
      - gpu
