# Self-Hosted Github Action Runners on GCP via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml.html
runners:
  - name: gpu-runner
    cloud: gcp
    gpu: nvidia-tesla-t4
    instance_type: n1-standard-1
    machine_image: ubuntu-minimal-2004-lts
    preemptible: false
    workflow: .github/workflows/tests-gpu.yml
    count: 1
    labels:
      - gpu
