# Self-Hosted Github Action Runners on AWS via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml.html
runners:
  - name: tests-gpu-runner
    cloud: aws
    region: eu-west-1
    instance_type: g4dn.xlarge  # Cheapest VM on AWS
    # Amazon AMI: Deep Learning AMI GPU CUDA 11.2.1 (Ubuntu 20.04) 20210625
    # for eu-west-1
    machine_image: ami-07b138161bedd526d
    preemptible: false
    workflow: .github/workflows/tests-gpu.yml
    count: 1
    labels:
      - gpu

  - name: docs-gpu-runner
    cloud: aws
    region: eu-west-1
    instance_type: g4dn.xlarge  # Cheapest VM on AWS
    # Amazon AMI: Deep Learning AMI GPU CUDA 11.2.1 (Ubuntu 20.04) 20210625
    # for eu-west-1
    machine_image: ami-07b138161bedd526d
    preemptible: false
    workflow: .github/workflows/docs-gpu.yml
    count: 1
    labels:
      - gpu
