name: Documentation of GPU

on:
  [push, pull_request]

jobs:
  build:
    name: Build HTML documentation
    runs-on: [self-hosted, gpu]

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        env:
          CONDA: /home/runnerx/miniconda3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"

      - name: Install documentation dependencies
        run: |
          python -mpip install -r doc/requirements.txt

      - name: Install QuTiP from GitHub
        run: |
          python -mpip install git+https://github.com/qutip/qutip.git@dev.major
          python -c 'import qutip; qutip.about()'

      - name: Install qutip-cupy from GitHub
        run: |
          conda install cupy
          python -mpip install .[full]
          python -c 'import qutip_cupy; print(qutip_cupy.__version__)'

      - name: Build documentation
        working-directory: doc
        run: |
          make html

      - name: Upload built files
        uses: actions/upload-artifact@v2
        with:
          name: qutip-cupy_html_docs
          path: doc/_build/html/*
          if-no-files-found: error
